apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui
  labels:
    app: karsajobs-ui
    tier: frontend
 #spesifikasi service
spec:
   #type layanan NodePort
  type: NodePort
   #port yang akan digunakan untuk service
  ports:
    - port: 8000
    #selector yang akan digunakan untuk memilih pods yang akan jadi target
  selector:
    app: karsajobs-ui